export interface Track {
  id: string
  title: string
  artists: string[]
  album: string
  year: number
  duration_ms: number
  cover_url: string
  audio_url: string
  spotify_url: string
  added_by: {
    name: string
    avatar: string
  }
  added_at: Date
  reactions: {
    like: number
    fire: number
    heart: number
  }
  genres: string[]
  moods: string[]
}

export const MOCK_TRACKS: Track[] = [
  {
    id: "1",
    title: "Essence",
    artists: ["Wizkid", "Tems"],
    album: "Made in Lagos",
    year: 2020,
    duration_ms: 216000,
    cover_url: "/wizkid-essence-album-art.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    spotify_url: "https://open.spotify.com/track/1",
    added_by: { name: "Alex Chen", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 3 * 60 * 60 * 1000),
    reactions: { like: 23, fire: 12, heart: 5 },
    genres: ["Afrobeats", "Pop"],
    moods: ["Uplifting", "Energetic"],
  },
  {
    id: "2",
    title: "Ye",
    artists: ["Burna Boy"],
    album: "Love, Damini",
    year: 2022,
    duration_ms: 198000,
    cover_url: "/burna-boy-ye-album.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    spotify_url: "https://open.spotify.com/track/2",
    added_by: { name: "Jordan Smith", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 5 * 60 * 60 * 1000),
    reactions: { like: 18, fire: 9, heart: 3 },
    genres: ["Afrobeats", "Hip-Hop"],
    moods: ["Reflective", "Smooth"],
  },
  {
    id: "3",
    title: "Essence (Remix)",
    artists: ["Rema", "Selena Gomez"],
    album: "Rema & Selena Gomez",
    year: 2022,
    duration_ms: 204000,
    cover_url: "/rema-selena-gomez-remix.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    spotify_url: "https://open.spotify.com/track/3",
    added_by: { name: "Maya Patel", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 2 * 60 * 60 * 1000),
    reactions: { like: 31, fire: 15, heart: 8 },
    genres: ["Afrobeats", "Pop"],
    moods: ["Uplifting", "Romantic"],
  },
  {
    id: "4",
    title: "Amapiano Vibes",
    artists: ["DBN Gogo", "Focalistic"],
    album: "Amapiano Sessions",
    year: 2023,
    duration_ms: 240000,
    cover_url: "/amapiano-vibes.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    spotify_url: "https://open.spotify.com/track/4",
    added_by: { name: "Chris Lee", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 1 * 60 * 60 * 1000),
    reactions: { like: 27, fire: 14, heart: 6 },
    genres: ["Amapiano", "Electronic"],
    moods: ["Energetic", "Danceable"],
  },
  {
    id: "5",
    title: "Essence of Life",
    artists: ["CKay"],
    album: "Boyfriend (Remix)",
    year: 2021,
    duration_ms: 210000,
    cover_url: "/ckay-essence-of-life.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    spotify_url: "https://open.spotify.com/track/5",
    added_by: { name: "Sarah Johnson", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 8 * 60 * 60 * 1000),
    reactions: { like: 22, fire: 11, heart: 7 },
    genres: ["Afrobeats", "R&B"],
    moods: ["Smooth", "Romantic"],
  },
  {
    id: "6",
    title: "Essence (Acoustic)",
    artists: ["Wizkid"],
    album: "Acoustic Sessions",
    year: 2023,
    duration_ms: 195000,
    cover_url: "/wizkid-acoustic.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    spotify_url: "https://open.spotify.com/track/6",
    added_by: { name: "David Kim", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 12 * 60 * 60 * 1000),
    reactions: { like: 19, fire: 8, heart: 4 },
    genres: ["Afrobeats", "Acoustic"],
    moods: ["Intimate", "Reflective"],
  },
  {
    id: "7",
    title: "Essence (EDM Remix)",
    artists: ["Wizkid", "Calvin Harris"],
    album: "Remixes",
    year: 2021,
    duration_ms: 228000,
    cover_url: "/wizkid-edm-remix.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    spotify_url: "https://open.spotify.com/track/7",
    added_by: { name: "Emma Wilson", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 24 * 60 * 60 * 1000),
    reactions: { like: 25, fire: 13, heart: 5 },
    genres: ["EDM", "Electronic"],
    moods: ["Energetic", "Danceable"],
  },
  {
    id: "8",
    title: "Essence (R&B Remix)",
    artists: ["Wizkid", "H.E.R."],
    album: "Remixes",
    year: 2021,
    duration_ms: 215000,
    cover_url: "/wizkid-r.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    spotify_url: "https://open.spotify.com/track/8",
    added_by: { name: "Lisa Anderson", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 36 * 60 * 60 * 1000),
    reactions: { like: 20, fire: 10, heart: 6 },
    genres: ["R&B", "Soul"],
    moods: ["Smooth", "Romantic"],
  },
  {
    id: "9",
    title: "Calm Down",
    artists: ["Rema"],
    album: "Rave & Roses",
    year: 2022,
    duration_ms: 235000,
    cover_url: "/rema-calm-down.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    spotify_url: "https://open.spotify.com/track/9",
    added_by: { name: "Tunde Adebayo", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 2 * 60 * 60 * 1000),
    reactions: { like: 34, fire: 18, heart: 10 },
    genres: ["Afrobeats", "Pop"],
    moods: ["Chill", "Romantic"],
  },
  {
    id: "10",
    title: "Soweto",
    artists: ["Victony", "Tempoe"],
    album: "Soweto EP",
    year: 2022,
    duration_ms: 210000,
    cover_url: "/victony-soweto.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    spotify_url: "https://open.spotify.com/track/10",
    added_by: { name: "John Park", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 9 * 60 * 60 * 1000),
    reactions: { like: 40, fire: 21, heart: 14 },
    genres: ["Afrobeats", "R&B"],
    moods: ["Relaxed", "Smooth"],
  },
  {
    id: "11",
    title: "Peru",
    artists: ["Fireboy DML", "Ed Sheeran"],
    album: "Peru (Remix)",
    year: 2022,
    duration_ms: 205000,
    cover_url: "/fireboy-peru.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    spotify_url: "https://open.spotify.com/track/11",
    added_by: { name: "Grace Liu", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 7 * 60 * 60 * 1000),
    reactions: { like: 29, fire: 13, heart: 9 },
    genres: ["Afrobeats", "Pop"],
    moods: ["Happy", "Danceable"],
  },
  {
    id: "12",
    title: "Bloody Samaritan",
    artists: ["Ayra Starr"],
    album: "19 & Dangerous",
    year: 2021,
    duration_ms: 200000,
    cover_url: "/ayra-bloody-samaritan.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
    spotify_url: "https://open.spotify.com/track/12",
    added_by: { name: "Daniel Carter", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 5 * 60 * 60 * 1000),
    reactions: { like: 37, fire: 19, heart: 11 },
    genres: ["Afrobeats", "Pop"],
    moods: ["Confident", "Energetic"],
  },
  {
    id: "13",
    title: "Last Last",
    artists: ["Burna Boy"],
    album: "Love, Damini",
    year: 2022,
    duration_ms: 212000,
    cover_url: "/burna-last-last.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3",
    spotify_url: "https://open.spotify.com/track/13",
    added_by: { name: "Ella Rodriguez", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 14 * 60 * 60 * 1000),
    reactions: { like: 42, fire: 25, heart: 17 },
    genres: ["Afrobeats", "R&B"],
    moods: ["Reflective", "Emotional"],
  },
  {
    id: "14",
    title: "Monalisa",
    artists: ["Lojay", "Sarz"],
    album: "LV N ATTN",
    year: 2021,
    duration_ms: 208000,
    cover_url: "/lojay-monalisa.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3",
    spotify_url: "https://open.spotify.com/track/14",
    added_by: { name: "Faith Mensah", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 16 * 60 * 60 * 1000),
    reactions: { like: 31, fire: 17, heart: 10 },
    genres: ["Afrobeats", "Soul"],
    moods: ["Sensual", "Calm"],
  },
  {
    id: "15",
    title: "Ku Lo Sa",
    artists: ["Oxlade"],
    album: "Ku Lo Sa - A COLORS Show",
    year: 2022,
    duration_ms: 193000,
    cover_url: "/oxlade-kulosa.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3",
    spotify_url: "https://open.spotify.com/track/15",
    added_by: { name: "Aaron Green", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 4 * 60 * 60 * 1000),
    reactions: { like: 33, fire: 18, heart: 12 },
    genres: ["Afrobeats", "R&B"],
    moods: ["Romantic", "Smooth"],
  },
  {
    id: "16",
    title: "Unavailable",
    artists: ["Davido", "Musa Keys"],
    album: "Timeless",
    year: 2023,
    duration_ms: 240000,
    cover_url: "/davido-unavailable.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3",
    spotify_url: "https://open.spotify.com/track/16",
    added_by: { name: "Chloe Brown", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 10 * 60 * 60 * 1000),
    reactions: { like: 36, fire: 22, heart: 15 },
    genres: ["Afrobeats", "Amapiano"],
    moods: ["Energetic", "Playful"],
  },
  {
    id: "17",
    title: "Rush",
    artists: ["Ayra Starr"],
    album: "Rush (Single)",
    year: 2023,
    duration_ms: 205000,
    cover_url: "/ayra-rush.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-17.mp3",
    spotify_url: "https://open.spotify.com/track/17",
    added_by: { name: "Leo Tran", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 6 * 60 * 60 * 1000),
    reactions: { like: 38, fire: 19, heart: 14 },
    genres: ["Afrobeats", "Pop"],
    moods: ["Confident", "Vibrant"],
  },
  {
    id: "18",
    title: "Terminator",
    artists: ["Asake"],
    album: "Mr. Money With The Vibe",
    year: 2022,
    duration_ms: 220000,
    cover_url: "/asake-terminator.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-18.mp3",
    spotify_url: "https://open.spotify.com/track/18",
    added_by: { name: "Hannah Kim", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 15 * 60 * 60 * 1000),
    reactions: { like: 44, fire: 26, heart: 18 },
    genres: ["Afrobeats", "Amapiano"],
    moods: ["Energetic", "Joyful"],
  },
  {
    id: "19",
    title: "Pana",
    artists: ["Tekno"],
    album: "Pana (Single)",
    year: 2017,
    duration_ms: 218000,
    cover_url: "/tekno-pana.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-19.mp3",
    spotify_url: "https://open.spotify.com/track/19",
    added_by: { name: "Sophia Wright", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 18 * 60 * 60 * 1000),
    reactions: { like: 28, fire: 12, heart: 8 },
    genres: ["Afrobeats", "Pop"],
    moods: ["Chill", "Romantic"],
  },
  {
    id: "20",
    title: "Attention",
    artists: ["Omah Lay", "Justin Bieber"],
    album: "Attention (Single)",
    year: 2022,
    duration_ms: 209000,
    cover_url: "/omahlay-attention.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-20.mp3",
    spotify_url: "https://open.spotify.com/track/20",
    added_by: { name: "Noah Davis", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 20 * 60 * 60 * 1000),
    reactions: { like: 32, fire: 15, heart: 9 },
    genres: ["Afrobeats", "R&B"],
    moods: ["Smooth", "Sensual"],
  },
  {
    id: "21",
    title: "Love Nwantiti",
    artists: ["CKay"],
    album: "CKay the First",
    year: 2021,
    duration_ms: 210000,
    cover_url: "/ckay-love.jpg",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-21.mp3",
    spotify_url: "https://open.spotify.com/track/21",
    added_by: { name: "Ifeanyi Udeh", avatar: "/diverse-avatars.png" },
    added_at: new Date(Date.now() - 17 * 60 * 60 * 1000),
    reactions: { like: 50, fire: 33, heart: 22 },
    genres: ["Afrobeats", "R&B"],
    moods: ["Romantic", "Dreamy"],
  },
]

export const GENRES = ["Afrobeats", "Amapiano", "Hip-Hop", "R&B", "Pop", "EDM", "Acoustic", "Electronic", "Soul"]

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest" },
  { value: "oldest", label: "Oldest" },
  { value: "most-reacted", label: "Most Reacted" },
  { value: "a-z", label: "A → Z" },
]
